Create main page
PurpleHead/wizard pull request #6
Opened 2024-10-31 12:25 UTC by PurpleHead

![image](https://github.com/user-attachments/assets/70afa078-372c-44e0-972d-e8c59cfebe64)

2024-11-03 14:29 UTC, 424ever commented
rebased onto current master for docker containers

2024-11-03 14:56 UTC, 424ever requested changes

2024-11-03 14:56 UTC, 424ever commented on wizard-client/angular.json
> +    "analytics": false
why not?

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/app.component.html
> +<div class="app-wrapper">
`wizard-wrapper`?
```diff
diff --git a/wizard-client/src/app/app.component.html b/wizard-client/src/app/app.component.html
index ec53c5d..24baed1 100644
--- a/wizard-client/src/app/app.component.html
+++ b/wizard-client/src/app/app.component.html
@@ -1,4 +1,4 @@
-<div class="app-wrapper">
+<div class="wizard-wrapper">
   <wizard-background>
     <wizard-header></wizard-header>
     <router-outlet></router-outlet>
diff --git a/wizard-client/src/app/app.component.scss b/wizard-client/src/app/app.component.scss
index c8e1bcf..295a3f9 100644
--- a/wizard-client/src/app/app.component.scss
+++ b/wizard-client/src/app/app.component.scss
@@ -1,4 +1,4 @@
-.app-wrapper {
+.wizard-wrapper {
   height: 100%;
   width: 100%;
   overflow: auto;

```

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/app.component.ts
>    selector: 'app-root',
`wizard-root`?
```diff
diff --git a/wizard-client/src/app/app.component.ts b/wizard-client/src/app/app.component.ts
index ce255fa..0030b33 100644
--- a/wizard-client/src/app/app.component.ts
+++ b/wizard-client/src/app/app.component.ts
@@ -1,14 +1,13 @@
-import { Component } from '@angular/core';
-import { RouterOutlet } from '@angular/router';
-import {HeaderComponent} from './components/header/header.component';
-import {BackgroundComponent} from './components/background/background.component';
+import { Component } from "@angular/core";
+import { RouterOutlet } from "@angular/router";
+import { HeaderComponent } from "./components/header/header.component";
+import { BackgroundComponent } from "./components/background/background.component";
 
 @Component({
-  selector: 'app-root',
+  selector: "wizard-root",
   standalone: true,
   imports: [RouterOutlet, HeaderComponent, BackgroundComponent],
-  templateUrl: './app.component.html',
-  styleUrl: './app.component.scss'
+  templateUrl: "./app.component.html",
+  styleUrl: "./app.component.scss",
 })
-export class AppComponent {
-}
+export class AppComponent {}
diff --git a/wizard-client/src/index.html b/wizard-client/src/index.html
index 3fa1305..a426ef8 100644
--- a/wizard-client/src/index.html
+++ b/wizard-client/src/index.html
@@ -1,13 +1,13 @@
 <!doctype html>
 <html lang="en">
-<head>
-  <meta charset="utf-8">
-  <title>Wizard</title>
-  <base href="/">
-  <meta name="viewport" content="width=device-width, initial-scale=1">
-  <link rel="icon" type="image/x-icon" href="icon.png">
-</head>
-<body>
-  <app-root></app-root>
-</body>
+  <head>
+    <meta charset="utf-8" />
+    <title>Wizard</title>
+    <base href="/" />
+    <meta name="viewport" content="width=device-width, initial-scale=1" />
+    <link rel="icon" type="image/x-icon" href="icon.png" />
+  </head>
+  <body>
+    <wizard-root></wizard-root>
+  </body>
 </html>

```

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/app.component.scss
> +.app-wrapper {
also wizard-wrapper

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/components/games/games.component.ts
component is not reachable

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/components/header/header.component.html
> +  <span class="btn" (click)="elementClicked.emit(HeaderElement.GAMES)">Scoreboard</span>
why like this? why not make these navigate via `routerLink`?

2024-11-03 14:56 UTC, 424ever commented on wizard-client/public/cards/c9.png
this image is 750x1000px, but displayed as 150x200px

2024-11-03 14:56 UTC, 424ever commented on wizard-client/src/app/components/home/home.component.html
> +  <img class="z z1 float4" src="cards/c9.png" width="150" style="top: 10vh; left: 80vw">
these sized should use relative units

2024-11-18 23:33 UTC, PurpleHead commented on wizard-client/angular.json
> +    "analytics": false
why yes

2024-11-18 23:38 UTC, PurpleHead commented on wizard-client/public/cards/c9.png
Jonas,
juckt

2024-11-18 23:41 UTC, PurpleHead commented on wizard-client/public/cards/c9.png
can also be reused somewhere else later imo

2024-11-21 16:04 UTC, 424ever commented on wizard-client/public/cards/c9.png
hmmmmhmmhmmmhhhmmm

2025-03-05 16:24 UTC, closed without merging